
modLoader="javafml"

loaderVersion="${loader_version_range}"

license="MIT"

[[mods]]
modId="deltaforcemod"
version="1.0.0"
displayName="三角洲行动 | 全面战场-占领据点"
authors="MINECRAFT_SNAS"
logoFile="deltaforce.png"
description='''
三角洲行动兵力,据点系统模组
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"